apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-metrics-deployment
  labels:
    app: flask-metrics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-metrics
  template:
    metadata:
      labels:
        app: flask-metrics
    spec:
      containers:
      - name: flask-metrics
        image: iabdraheem/flask-metrics:1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
