apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: flask-metrics-keda
spec:
  scaleTargetRef:
    name: flask-metrics-deployment
  minReplicaCount: 2
  maxReplicaCount: 5
  pollingInterval: 15
  cooldownPeriod: 30
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "70"
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-operated.monitoring.svc.cluster.local:9090
        metricName: http_requests_total
        threshold: "50"
        query: avg(rate(http_requests_total[1m])) * 60

