apiVersion: keda/v1alpha1
kind: ScaledObject
metadata:
  name: flask-metrics-keda
spec:
  scaleTargetRef:
    name: flask-metrics-deployment
  minReplicaCount: 2
  maxReplicaCount: 5
  cooldownPeriod: 30
  poolingInterval: 15
  trigger:
    - type: Prometheus
      metadata:
        serverAddress: http://my-Prometheus-community.default.svc.cluster.local
        metricsName: http_requests_total
        treshold: "50"
        query: |
          sum(avg(http_requests_total[1])) by (pod)
