apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-metrics
  namespace: default
  labels:
    release: prometheus-operator
spec:
    selector:
      matchLabels:
        app: flask-metrics
    endpoints:
      - port: metrics
        path: /metrics
        interval: 15s