apiVersion: v1
kind: Service
metadata:
  name: flask-metrics-service
  labels:
    app: flask-metrics
spec:
  selector:
    app: flask-metrics
  ports:
    - protocol: TCP
      name: metrics
      port: 80
      targetPort: 3000
  type: LoadBalancer
